// Auto-generated by scripts/build-verified.ts
// DO NOT EDIT MANUALLY

export const VERIFIED_EPISODE_COUNT = 50;
export const VERIFIED_QUOTE_COUNT = 583;

export const ZONE_EPISODE_COUNTS = {
  "velocity": 45,
  "perfection": 39,
  "discovery": 48,
  "data": 39,
  "intuition": 44,
  "alignment": 48,
  "chaos": 43,
  "focus": 50
} as const;

export const VERIFIED_EPISODE_SLUGS = [
  "aishwarya-naresh-reganti-kiriti-badam",
  "ami-vora",
  "amjad-masad",
  "annie-duke",
  "anton-osika",
  "april-dunford-20",
  "ben-horowitz",
  "boz",
  "brian-chesky",
  "camille-fournier",
  "casey-winters-20",
  "casey-winters",
  "claire-hughes-johnson",
  "dalton-caldwell",
  "deb-liu",
  "dharmesh-shah",
  "drew-houston",
  "dylan-field-20",
  "dylan-field",
  "elena-verna-30",
  "eric-ries",
  "gibson-biddle",
  "gokul-rajaram",
  "guillermo-rauch",
  "howie-liu",
  "ivan-zhao",
  "jason-fried",
  "julie-zhuo-20",
  "kim-scott",
  "kunal-shah",
  "lulu-cheng-meservey",
  "maggie-crowley",
  "marty-cagan-20",
  "melanie-perkins",
  "mike-krieger",
  "molly-graham",
  "naomi-gleit",
  "nikita-bier",
  "nir-eyal",
  "paul-adams",
  "rahul-vohra",
  "ravi-mehta",
  "ryan-hoover",
  "scott-belsky",
  "shishir-mehrotra",
  "shreyas-doshi",
  "stewart-butterfield",
  "teresa-torres",
  "tobi-lutke",
  "wes-kao-20"
] as const;
