// Auto-generated by scripts/build-verified.ts
// DO NOT EDIT MANUALLY

export const VERIFIED_EPISODE_COUNT = 18;
export const VERIFIED_QUOTE_COUNT = 211;

export const ZONE_EPISODE_COUNTS = {
  "velocity": 14,
  "perfection": 16,
  "discovery": 16,
  "data": 14,
  "intuition": 14,
  "alignment": 16,
  "chaos": 14,
  "focus": 18
} as const;

export const VERIFIED_EPISODE_SLUGS = [
  "aishwarya-naresh-reganti-kiriti-badam",
  "amjad-masad",
  "annie-duke",
  "april-dunford",
  "boz",
  "brian-chesky",
  "casey-winters",
  "dylan-field",
  "elena-verna",
  "gokul-rajaram",
  "jason-fried",
  "julie-zhuo",
  "marty-cagan",
  "nikita-bier",
  "rahul-vohra",
  "shreyas-doshi",
  "stewart-butterfield",
  "tobi-lutke"
] as const;
